### ISSUE TITLE
Query:How to enable gzip compression

### ISSUE THREAD

**Issue by vsharma02** [heroku/heroku-buildpack-java#102]
This may be a bit lame question. I am using spring MVC REST, Is there a way to enable gzip compression using Heroku build pack for that or is there any way by which I can change the server.xml?

**Comment by jkutner** [comment]
@vsharma02 not a lame question at all. Are you using [webapp-runner](https://github.com/jsimone/webapp-runner)? If so, you can add the `--enable-compression` option to your `java` command. Otherwise, it will depend on the framework or server you're using.

**Comment by vsharma02** [comment]
@jkutner , Thanks a lot! It worked
