### ISSUE TITLE
Could not detect buildpack /  Error compiling buildpack

### ISSUE THREAD

**Issue by danawoodman** [heroku/heroku-buildpack-java#104]
Reproduce:

- Create app on Heroku with CI
- Add the `heroku/java` buildpack:

![](https://cl.ly/c4ddf7d0de5f/Screen%20Shot%202018-09-13%20at%204.21.02%20PM.png)

- The buildpack shows correctly under the app:

![](https://cl.ly/85db59b6a1bc/Screen%20Shot%202018-09-13%20at%204.20.29%20PM.png)

- However, running CI fails on the Java buildpack:

![](https://cl.ly/13473e94f198/Screen%20Shot%202018-09-13%20at%204.21.28%20PM.png)

Anything I'm missing to get this working?

PS I'm adding the java buildpack to run selenium tests for my node/react app in case that is useful info

**Comment by jkutner** [comment]
@danawoodman does your app have a `pom.xml`? If not, I think you may want the `heroku/jvm` buildpack instead (and you probably would want it before the node buildpack so that the JVM is available during it's execution).

**Comment by danawoodman** [comment]
Ah, that would make sense. Let me try that and report back. Thanks! 👍

**Comment by jkutner** [comment]
I'm going to close this, but we can reopen if you still have issues.
