### ISSUE TITLE
Cache dir not automatically created?

### ISSUE THREAD

**Issue by sean-zou** [heroku/heroku-buildpack-java#111]
We started getting this error after this commit: https://github.com/heroku/heroku-buildpack-java/commit/db89ce68fae81d30bb7478e0a72c3666086941b5, looks like cache dir was not automatically created when writing the system.properties file to it.

buildpacks/java/bin/compile /var/EUAD4ABKBEIC7F63IDQJVTVF5ATUY6DZYKUQTKT2FUOR3Z76I5WQ/app-71 /var/EUAD4ABKBEIC7F63IDQJVTVF5ATUY6DZYKUQTKT2FUOR3Z76I5WQ/cache-71
-----> Installing JDK 1.8.../tmp/jvm-common/bin/java: line 302: /var/EUAD4ABKBEIC7F63IDQJVTVF5ATUY6DZYKUQTKT2FUOR3Z76I5WQ/cache-71/system.properties: No such file or directory

**Comment by jkutner** [comment]
@sean-zou i assume this is not running on heroku, is that correct? In any case, it seems like a `mkdir -p $CACHE_DIR` will prevent this from happening.

**Comment by sean-zou** [comment]
It is not running on heroku. It was working fine before the commit.

**Comment by jkutner** [comment]
@sean-zou this will need to be fixed in the [heroku/jvm buildpack](https://github.com/heroku/heroku-buildpack-jvm-common). I've created a PR for it.

**Comment by jkutner** [comment]
Fixed by https://github.com/heroku/heroku-buildpack-jvm-common/pull/87
