### ISSUE TITLE
Maven wrapper not used

### ISSUE THREAD

**Issue by bherzig-nist** [heroku/heroku-buildpack-java#121]
Hi there,

we have a spring boot application which uses the maven wrapper but the buildpack does not detect the maven wrapper for the test setup. We went through the scripts and it should work but it doesn't

Do you have a suggestion what might go wrong?

**Comment by jkutner** [comment]
@bherzig-nist can you share some details about your app? In particular the output of `heroku buildpacks`, and `git ls-files`.

If you need to share information privately, please open a [support ticket](https://help.heroku.com/).

**Comment by bherzig-nist** [comment]
Hi @jkutner,
thanks for your response.

`git ls-files`:
```
.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
.slug-post-clean
Procfile
README.md
app.json
mvnw
mvnw.cmd
pom.xml
settings.xml
system.properties
```
I've curated the list to remove the noise of our source code.

`heroku buildpacks`:
```
1. heroku/java
2. https://github.com/Lostmyname/heroku-buildpack-post-build-clean
```

`system.properties`:
```
java.runtime.version=12
```

**Comment by jkutner** [comment]
@bherzig-nist thanks, it's not immediately obvious to me what's wrong. Can you open a [support ticket](https://help.heroku.com) so we can take a closer look?

**Comment by bherzig-nist** [comment]
@jkutner I've opened a support ticket #794825
Thanks so far.

Shall we let this ticket here open and post a solution in the end? Maybe other may face a similar issue.
