### ISSUE TITLE
Corporate Proxy

### ISSUE THREAD

**Issue by dirien** [heroku/heroku-buildpack-java#132]
Hi,

we want to use the buildpack in our on-premise cloud foundry installation.

Unfortunatly, we are behind a corportate proxy.

Could you list the URL we need to whiltelist to download maven/jdk/zulu-jdk?

Cheers

**Comment by Malax** [comment]
Hello,

JDKs as well as Maven (if not using Maven Wrapper) are downloaded from `https://lang-jvm.s3.amazonaws.com/` as the base URL.

**Comment by dirien** [comment]
@Malax Thanks a lot!
