### ISSUE TITLE
Unmanaged dependency failed to be resolved

### ISSUE THREAD

**Issue by fgarsombke** [heroku/heroku-buildpack-java#26]
I followed the instructions from:

https://devcenter.heroku.com/articles/local-maven-dependencies

When I push my app to Heroku it can not find the added jar in its local repository. This works fine on my local instance. 

[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project com.h2lo:api:jar:1.0: Could not find artifact pubnub:pubnub-java:jar:3.4 in project.local (file:/tmp/build_30y04zs5a9clk/repo) -> [Help 1]

Thoughts?

Thanks in advance.

Franz Garsombke

**Comment by fconza191185** [comment]
hi, @jcouyang thanks for you help.

**Comment by RaghavPro** [comment]
Thanks @jcouyang for saving the day.

**Comment by dxyv** [comment]
Thanks @jcouyang u saved my day
