### ISSUE TITLE
Install Java without Maven

### ISSUE THREAD

**Issue by d10** [heroku/heroku-buildpack-java#57]
Is it possible to just install Java without building apps with Maven? My use case is just to create an app that has both Node and Java environments (with multi-buildpack) to run Closure Compiler, so it does not actually need to build Java apps.

**Comment by jkutner** [comment]
Yes, for that you can use the jvm-common buildpack. Your `.buildpacks` file would look like this:

```
https://github.com/heroku/heroku-buildpack-jvm-common.git
https://github.com/heroku/heroku-buildpack-nodejs.git
```

Also, the cedar-14 image has a JDK 7u75 distribution installed by default -- so you may not even need the jvm-common buildpack. But if you want JDK 8 you will need it.

(I'm going to close this but feel free to keep the discussion going, and we can even reopen it if the above does not work).

**Comment by d10** [comment]
Yeah, I created this issue because I didn't find anything about the jvm-common buildpack. Thanks anyway!

**Comment by jkutner** [comment]
I'll add some documentation to the buildpack readme.
