### ISSUE TITLE
pom.xml not in root

### ISSUE THREAD

**Issue by weslley39** [heroku/heroku-buildpack-java#60]
In my project, i do not have the pom.xml in my root, when i do a push, heroku says that my app was not detected. How can i specify where my pom.xml is ?

My pom.xml is in:
`./app-name-serve/pom.xml`

**Comment by jkutner** [comment]
At this time the buildpack does not support Java apps in a subdirectory. If it's necessary to structure your app this way, then I suggest making the root directory a simple Maven parent, and including your sub-dir as a Maven submodule.

Working with submodules is described in the [Maven documention](https://maven.apache.org/guides/mini/guide-multiple-modules.html).

**Comment by Puskin2911** [comment]
At this time, is heroku support for this problem ?

**Comment by saurav28** [comment]
This issue is still not solved.
Having a mono repo kind of project is very difficult if this not solved
