### ISSUE TITLE
Cloud Foundry uploading everything?

### ISSUE THREAD

**Issue by MTyson** [heroku/heroku-buildpack-java#65]
I have this defined in my manifest.yml:

- path: .
  memory: 500m
  name: my-group-my-project-test
  env:
    FOO_BAR: test
  buildpack: https://github.com/heroku/heroku-buildpack-java

When I run:

cf push my-group-my-project-test

In my root directory, where pom.xml resides, I expected the application files to be uploaded, and the dependencies to be pulled down by maven on the platform. 

What is happening is that everything on local, including dependencies, is being uploaded (to the tune of 56 megs).  Am I missing the purpose of this buildpack?  I thought the point was to download and cache the dependencies on the platform to improve performance.

**Comment by jkutner** [comment]
This buildpack is not aware of `manifest.yml`. That is a Cloud Foundry feature of `cf push`, which is independent of the buildpack. You'll have to reference the [Cloud Foundry docs on manifest.yml](http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html).

**Comment by MTyson** [comment]
Thanks for your reply, @jkutner .  I'm really driving at the buildpack behavior.  Is it true that this buildpack downloads the maven deps on the platform, or does it upload them from the client?

**Comment by jkutner** [comment]
@MTyson it downloads the deps during the build (on the platform). It does not take them from the client. However, the `cf push` command (which is not related to this project) might be uploading your `target/` directory based on some improper configuration.

**Comment by MTyson** [comment]
@jkutner ah ok.  I actually did a mvn clean, so there's no /target dir after I saw your response, but I still see this:

Uploading 30.6M, 14532 files

when I do a cf push (not using manifest.yml).

Any thoughts where I should look into what is happening?

**Comment by jkutner** [comment]
@MTyson I have no idea. I don't use Cloud Foundry. I would ask some folks at Pivotal

**Comment by MTyson** [comment]
@jkutner Can I ask how you use the buildpack?  I am only familiar with the cloud foundry usage.

**Comment by jkutner** [comment]
@MTyson https://devcenter.heroku.com/articles/getting-started-with-java#introduction
