### ISSUE TITLE
buildpack test script does not use run_mvn helper

### ISSUE THREAD

**Issue by mjakl** [heroku/heroku-buildpack-java#90]
The test script uses the `mvn` directly ignoring all the settings that would have been set when using the `run_mvn` function. Especially the custom `settings.xml` is ignored which causes builds to compile, but fail during tests if there is still a dependency to download.

A workaround for now is to set the test script in `app.json`:

```json
  "scripts": {
      "test": "mvn -s settings.xml test"
  },
```

but maybe it would be nice to make the buildpack consistently using the `settings.xml`.

**Comment by jkutner** [comment]
I think there is a reason we don't use the `run_mvn` function for `bin/test`, but I'll have to look back at it. Certainly, I agree that it should pick up the `settings.xml` the same way as the other `mvn` commands. At a minimum I'll make sure it does that so the `app.json` is no longer required.

Thanks for reporting this. Sorry for the trouble.
